# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.find_or_create_by(pet_type: "Dog")
Category.find_or_create_by(pet_type: "Cat")
Category.find_or_create_by(pet_type: "Bird")
Category.find_or_create_by(pet_type: "Fish")
Category.find_or_create_by(pet_type: "Rabbit")
Category.find_or_create_by(pet_type: "Hamster")
Category.find_or_create_by(pet_type: "Mouse")
Category.find_or_create_by(pet_type: "Rat")
Category.find_or_create_by(pet_type: "Gerbil")
Category.find_or_create_by(pet_type: "Guinea Pig")
Category.find_or_create_by(pet_type: "Chinchilla")
Category.find_or_create_by(pet_type: "Ferret")
Category.find_or_create_by(pet_type: "Pig")
Category.find_or_create_by(pet_type: "Horse")
Category.find_or_create_by(pet_type: "Turtle/Tortoise")
Category.find_or_create_by(pet_type: "Frog/Toad")
Category.find_or_create_by(pet_type: "Snake")
Category.find_or_create_by(pet_type: "Lizard")
Category.find_or_create_by(pet_type: "Insect")
Category.find_or_create_by(pet_type: "Spider")
Category.find_or_create_by(pet_type: "Scorpion")
Category.find_or_create_by(pet_type: "Crab")
Category.find_or_create_by(pet_type: "Other")
